# Generated by Django 3.1.7 on 2021-02-26 20:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Predmet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('fer_url', models.CharField(max_length=60, unique=True)),
            ],
            options={
                'verbose_name_plural': 'Predmeti',
            },
        ),
        migrations.CreateModel(
            name='Komponenta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('predmet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fer_grades.predmet')),
            ],
            options={
                'verbose_name_plural': 'Komponente',
            },
        ),
    ]
