# Generated by Django 3.1.7 on 2021-02-26 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fer_grades', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='komponenta',
            name='max_points',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='komponenta',
            name='points_collected',
            field=models.FloatField(default=0),
        ),
    ]
