# Generated by Django 3.1.7 on 2021-02-26 21:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fer_grades', '0003_student_studentpredmet'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='komponenta',
            name='points_collected',
        ),
        migrations.CreateModel(
            name='KomponentaBodovi',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('points_collected', models.FloatField(default=0)),
                ('komponenta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fer_grades.komponenta')),
                ('predmet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fer_grades.studentpredmet')),
            ],
        ),
    ]
