# Generated by Django 3.1.7 on 2021-02-27 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fer_grades', '0004_auto_20210226_2127'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentpredmet',
            name='login_code',
            field=models.CharField(blank=True, max_length=6),
        ),
    ]
