# Generated by Django 3.1.7 on 2021-02-27 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fer_grades', '0005_studentpredmet_login_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentpredmet',
            name='login_code',
        ),
        migrations.AddField(
            model_name='student',
            name='login_code',
            field=models.CharField(blank=True, max_length=6),
        ),
    ]
