# Generated by Django 3.1.7 on 2021-02-27 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fer_grades', '0006_auto_20210227_1610'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='login_code',
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
    ]
