# Generated by Django 3.1.7 on 2021-02-27 18:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fer_grades', '0007_auto_20210227_1720'),
    ]

    operations = [
        migrations.CreateModel(
            name='Uvjeti',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uvjet_tekst', models.CharField(max_length=200)),
                ('predmet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fer_grades.predmet')),
            ],
        ),
    ]
