# Generated by Django 3.1.7 on 2021-02-27 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fer_grades', '0008_uvjeti'),
    ]

    operations = [
        migrations.AddField(
            model_name='komponenta',
            name='prag',
            field=models.FloatField(default=0),
        ),
    ]
