# Generated by Django 3.1.7 on 2021-02-27 22:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fer_grades', '0009_komponenta_prag'),
    ]

    operations = [
        migrations.AddField(
            model_name='komponentabodovi',
            name='description',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
