# Generated by Django 3.1.7 on 2021-02-28 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fer_grades', '0010_komponentabodovi_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='predmet',
            name='dobar',
            field=models.IntegerField(default=65),
        ),
        migrations.AddField(
            model_name='predmet',
            name='dovoljan',
            field=models.IntegerField(default=50),
        ),
        migrations.AddField(
            model_name='predmet',
            name='odlican',
            field=models.IntegerField(default=90),
        ),
        migrations.AddField(
            model_name='predmet',
            name='vrlo_dobar',
            field=models.IntegerField(default=75),
        ),
    ]
