# Generated by Django 3.1.7 on 2021-02-28 19:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fer_grades', '0012_predmet_creted_by'),
    ]

    operations = [
        migrations.RenameField(
            model_name='predmet',
            old_name='creted_by',
            new_name='created_by',
        ),
    ]
