# Generated by Django 3.1.7 on 2021-03-03 12:38

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fer_grades', '0013_auto_20210228_1935'),
    ]

    operations = [
        migrations.AlterField(
            model_name='komponenta',
            name='prag',
            field=models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1)]),
        ),
    ]
