# Generated by Django 3.1.7 on 2021-03-05 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fer_grades', '0014_auto_20210303_1238'),
    ]

    operations = [
        migrations.AddField(
            model_name='predmet',
            name='ects',
            field=models.IntegerField(default=5),
        ),
    ]
